<<<<<<< HEAD
=======
# Generated by Django 4.2.29 on 2026-03-13 20:23

>>>>>>> 85979af9c9ab7ae4dc87a2ca7b9ae268d7bb6f8b
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
    dependencies = []
=======
    dependencies = [
    ]
>>>>>>> 85979af9c9ab7ae4dc87a2ca7b9ae268d7bb6f8b

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=50)),
                ('cgpa', models.FloatField()),
                ('year', models.CharField(max_length=20)),
=======
                ('name', models.CharField(max_length=120)),
                ('branch', models.CharField(blank=True, choices=[('CSE', 'Computer Science Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Communication'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('DS', 'Data Science'), ('Other', 'Other')], max_length=10)),
                ('cgpa', models.FloatField(default=7.0)),
                ('year', models.CharField(blank=True, choices=[('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year'), ('grad', 'Graduated')], max_length=10)),
>>>>>>> 85979af9c9ab7ae4dc87a2ca7b9ae268d7bb6f8b
                ('leetcode', models.IntegerField(default=0)),
                ('github', models.IntegerField(default=0)),
                ('skills', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
<<<<<<< HEAD
        ),
        migrations.CreateModel(
            name='CareerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('skills_have', models.JSONField(default=list)),
                ('skills_missing', models.JSONField(default=list)),
                ('avg_salary', models.CharField(max_length=50)),
                ('demand_trend', models.CharField(max_length=50)),
                ('rank', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='careers.studentprofile')),
            ],
            options={
                'ordering': ['rank'],
=======
            options={
                'verbose_name': 'Student Profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results_json', models.JSONField(default=list)),
                ('top_career', models.CharField(max_length=200)),
                ('top_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='careers.studentprofile')),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'ordering': ['-created_at'],
>>>>>>> 85979af9c9ab7ae4dc87a2ca7b9ae268d7bb6f8b
            },
        ),
    ]
