# Generated by Django 4.2.29 on 2026-03-13 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('branch', models.CharField(blank=True, choices=[('CSE', 'Computer Science Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Communication'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('DS', 'Data Science'), ('Other', 'Other')], max_length=10)),
                ('cgpa', models.FloatField(default=7.0)),
                ('year', models.CharField(blank=True, choices=[('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year'), ('grad', 'Graduated')], max_length=10)),
                ('leetcode', models.IntegerField(default=0)),
                ('github', models.IntegerField(default=0)),
                ('skills', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results_json', models.JSONField(default=list)),
                ('top_career', models.CharField(max_length=200)),
                ('top_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='careers.studentprofile')),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'ordering': ['-created_at'],
            },
        ),
    ]
